### ISSUE TITLE
DF file version missmatch with programs

### ISSUE THREAD

**Issue by vjug** [patrickTingen/xref#1]
Program loadXref.p cannot be run because database is missing some definitions (** Unknown Field or Variable name - dtLastModified)

**Comment by patrickTingen** [comment]
Hi, thanks for reporting this. Could you give me a little more information on what you did before you got the error?

**Comment by vjug** [comment]
Included .df file for xref_XmlFile contains only two fields (cFullName, cLastModified) both of type character, and procedure uses date-time field bXmlFile.dtLastModified, line 191. Maybe latest version of .df file is not updated? 

    /* Check if file on disk has been changed since the last time */
    dtFileModified = DATETIME(FILE-INFO:FILE-MOD-DATE, FILE-INFO:FILE-MOD-TIME * 1000).
    IF bXmlFile.dtLastModified >= dtFileModified THEN RETURN.

**Comment by patrickTingen** [comment]
Ah, I see now. I updated the programs but forgot to update the df. I fixed it now with the latest commit 5183784285f5d67b3e8db3adf04dfc38c80db44b

**Comment by cverbiest** [comment]
@patrickTingen Could it be you inadvertently deleted xref_Environment from xrefdb.df

**Comment by patrickTingen** [comment]
Deleted yes, inadvertently no. This field was taken out to make the tool simpler. The field xref_Environment was cluttering up the schema

I see now that readFolder.p needs some adjustments as well. I will update this one shortly

**Comment by patrickTingen** [comment]
I have refreshed the complete package and tested it on own pc. It now just works :)
See also folder 'dogfood' for an example of how to use it.  Commit 5133783
